baseURL = "https://kaihuaqin.com/"
languageCode = "en-us"
title = "Kaihua Qin"
theme = "avicenna"
googleAnalytics = ""
timeout=3000

[params]
  subtitle= "Ph.D. Student"
  interests="Blockchain, Decentralized Finance (DeFi), System Security"
  cv_name= "KaihuaQin_CV.pdf"
  blog=""
  googlescholar = "https://scholar.google.com/citations?user=-NPCrhcAAAAJ&hl=en"

[[params.affilation]]
  name = "Imperial College London"
  position = "Ph.D. Student"
  contact = "kaihua.qin@imperial.ac.uk"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/KaihuaQin"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/KaihuaQIN"


[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/kaihua-qin-072118112/"


[[params.introduction.paragraph]]
  text="""
  I'm a Ph.D. student at [Imperial College London](https://www.imperial.ac.uk/), supervised by [Dr. Arthur Gervais](https://arthurgervais.com/).
  My research interests span blockchains and system security with a recent focus on decentralized finance (DeFi).
  DeFi is one of the most promising applications of blockchains.
  I'm motivated to understand the risks and vulnerabilities of the DeFi ecosystem.
  Many of the DeFi security issues are caused by the inherent properties of blockchains and flawed protocol designs.
  In my research, I'm trying to improve the security of DeFi from both the underlying blockchain and the high-level DeFi protocol perspective.
  """


[[params.publications]]
  year="Preprint"

  [[params.publications.paper]]
    name = "Quantifying Blockchain Extractable Value: How dark is the forest?"
    authors = "__Kaihua Qin__, Liyi Zhou, Arthur Gervais"
    link = "https://arxiv.org/abs/2101.05511"
	arxiv = "https://arxiv.org/abs/2101.05511"

[[params.publications]]
  year="2021"

  [[params.publications.paper]]
		name = "High-Frequency Trading on Decentralized On-Chain Exchanges"
		authors = "Liyi Zhou, __Kaihua Qin__, Christof Ferreira Torres, Duc V Le, Arthur Gervais"
		dest  = "to appear at the 42nd IEEE Symposium on Security and Privacy ([IEEE S&P 2021](https://www.ieee-security.org/TC/SP2021/))"
		link = "https://arxiv.org/abs/2009.14021"
		arxiv = "https://arxiv.org/abs/2009.14021"

  [[params.publications.paper]]
		name="Attacking the DeFi Ecosystem with Flash Loans for Fun and Profit"
		authors = "__Kaihua Qin__, Liyi Zhou, Benjamin Livshits, Arthur Gervais"
		link = "https://arxiv.org/abs/2003.03810"
		arxiv = "https://arxiv.org/abs/2003.03810"
		dest = "to appear at the Financial Cryptography and Data Security 2021 ([FC 21](https://fc21.ifca.ai/))"
		blog_link = "https://hackingdistributed.com/2020/03/11/flash-loans/"

[[params.publications]]
  year="2020"

  [[params.publications.paper]]
		name = "FileBounty: Fair Data Exchange"
		authors = "Simon Janin *, __Kaihua Qin__ *, Akaki Mamageishvili, Arthur Gervais"
		dest  = "in proceedings of the 2020 IEEE European Symposium on Security and Privacy Workshops ([IEEE S&B 2020](https://ieeesb.org/))"
		link = "https://ieeexplore.ieee.org/abstract/document/9229692"
		arxiv = "https://arxiv.org/abs/2008.11362"
		comments = "\\* _equal contributions_"

[[params.publications]]
  year="2019"

  [[params.publications.paper]]
  		name = "Applying Private Information Retrieval to Lightweight Bitcoin Clients"
		authors = "__Kaihua Qin__, Henryk Hadass, Arthur Gervais, Joel Reardon"
		dest  = "in proceedings of the 2019 Crypto Valley Conference on Blockchain Technology ([CVCBT 2019](https://www.cryptovalleyconference.com/))"
		link = "https://ieeexplore.ieee.org/abstract/document/8787550"
		arxiv = "https://arxiv.org/abs/2008.11358"

[[params.publications]]
  year="Report"

  [[params.publications.paper]]
  		name = "An Overview of Blockchain Scalability, Interoperability and Sustainability"
		authors = "__Kaihua Qin__, Arthur Gervais"
		dest  = "[EU Blockchain Observatory & Forum](https://www.eublockchainforum.eu/)"
		link = "https://www.eublockchainforum.eu/sites/default/files/research-paper/an_overview_of_blockchain_scalability_interoperability_and_sustainability.pdf"

[[params.projects]]
	[[params.projects.project]]
		name = "Blockchain Workbench (https://blockchainworkbench.com/)"
		description  = "Blockchain Workbench is a blockchain online learning platform.It aims to provide basic knowledge of blockchains and interactive solidity programming exercises to beginners.It has been used as the solidity educational platform for the blockchain courses at [Imperial College London](https://www.imperial.ac.uk/) and [HSLU](https://www.hslu.ch/en/)."
		project_page = "https://blockchainworkbench.com/"
